# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://igemhd.github.io
title: iGEM Heidelberg 2020
email: igemhd@protonmail.com
author: iGEM Heidelberg
description: > # "Write an awesome description for your new site here. 
  Welcome to the front desk of the iGEM Team Heidelberg 2020. Are you wondering
  whether iGEM is right for you? Then you've come to the right place.
  iGEM is – indeed – very right for you.
copyright: 'Copyright &copy; 2019 iGEM RC/Heidelberg. All Rights Reserved.'
credits: 'Credits: This is a free to use, open source Bootstrap theme based on Landing page, created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    icon: github
    url: https://github.com/igemhd
  - title: mail
    icon: envelope
    url: mailto:igemhd@protonmail.com
